### ISSUE TITLE
Launch crash - brandonscore unsupported version

### ISSUE THREAD

**Issue by hannaensor** [scalda/FoolCraft#1]
If you need to get in touch with me elsewhere - discord haleighen

[11:23:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:23:08] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:23:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:23:08] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2254 for Minecraft 1.10.2 loading
[11:23:08] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.12.3, installed at /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: java.lang.UnsupportedClassVersionError: com/brandon3055/brandonscore/asm/LoadingPlugin : Unsupported major.minor version 51.0
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.Class.forName0(Native Method)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at java.lang.Class.forName(Class.java:249)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:23:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:configureForClientLaunch:41]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:23:09] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/Nymeria/Library/Application Support/minecraft/Instances/FoolCraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: com/brandon3055/brandonscore/asm/LoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564) ~[forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425) ~[forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) ~[forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.3.2254.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Exception in thread "main"

**Comment by scalda** [comment]
Try updating your java to latest and up the ram allocation to 6gb

**Comment by hannaensor** [comment]
My java is already up to date and I also bumped up the ram allocation. I have 16gb installed - set to 6gb for minecraft so shouldn't have issues there. Still isn't working.

**Comment by HazDS** [comment]
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65

Can you confirm what Java version you are running now? Try installing Java1.8 if you haven't already?

**Comment by hannaensor** [comment]
Java 1.8 Update 121 installed

**Comment by HazDS** [comment]
Please can you post your latest crash log?

**Comment by hannaensor** [comment]
Seems to be working now! I installed the new twitch app this morning - I think the settings were conflicting with curse somehow. Restarted and now there are no issues.

Thanks!
