### ISSUE TITLE
Crashes Minecraft possibly due to item in inventory missing texture

### ISSUE THREAD

**Issue by znxster** [scalda/FoolCraft#1001]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

I busted a loot chest with an axe and collected the items it dropped. Then my MC crashed. Attempting to restart, it load all the way until I can see the game but then freezes and crashes.

I did notice however, that there is an item on my hot bar which has no texture, I am guessing it is the cause of my crash.

Due to a previous issue, the pack does not have the hats mod.

## Reproduce Steps
If I can work out what the item it, I would predict it could be reproduced.

## Additional Information

I am going to attempt to edit it out of my inventory.

I have a crash log but its 16M, so not sure what exactly to look for or if its appropriate to upload here?

I did note this within the log, maybe it indicates the item is a egg from the chickens mod?

```
[23:22:18] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at com.setycz.chickens.spawnEgg.ItemSpawnEgg.func_77653_i(ItemSpawnEgg.java:40) ~[ItemSpawnEgg.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:508) ~[adz.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:625) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:170) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072) ~[bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

```

**Comment by znxster** [comment]
Apologies just discovered the crash reports directory, see attached crash report!
[crash-2018-05-16_23.22.18-client.txt](https://github.com/scalda/FoolCraft/files/2011074/crash-2018-05-16_23.22.18-client.txt)

**Comment by znxster** [comment]
I have successfully removed the offending item from my inventory and loaded the game. It was indeed a spawn egg from the chickens mod.

NBTExplorer screenshot - https://imgur.com/a/ihh2hIq
