### ISSUE TITLE
Foolcraft 3 keeps crashing before the stating menu

### ISSUE THREAD

**Issue by StocialAbyss** [scalda/FoolCraft#1011]
It keeps crashing

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
Its crashes during the installing mods screen

## Reproduce Steps

---- Minecraft Crash Report ----
// Don't do that.

Time: 5/28/18 3:12 PM
Description: Initializing game

java.nio.file.ProviderNotFoundException: Provider not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:638)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:618)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:638)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:618)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 616291568 bytes (587 MB) / 969408512 bytes (924 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xmx8G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2673 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.3.2673.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge     | 14.23.3.2673 | forge-1.12.2-14.23.3.2673.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: forge-14.23.3.2673
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
