### ISSUE TITLE
Things disappear when I unload chunks

### ISSUE THREAD

**Issue by calabazY** [scalda/FoolCraft#224]
When I unload chucks or go to a dimension some things I have done recentrly disappear or go to the past. for exampe i put some fish in the alloy , and it finishes but when i unload it starts again, same with blocks.

**Comment by calabazY** [comment]
Also I think the problem happens near my machines that include, crafting grid, two energy cells, a solderer an alloy smelter, 2 magmatic generators an rf storage controller compresion and magmatic dynamo and soem cables.

**Comment by Jo-Mamma75** [comment]
Sounds like it's not saving properly.  If this is in a single player world, do you have sufficient free hard drive space and have you checked your hard drive for bad sectors?

**Comment by calabazY** [comment]
[11:18:44] [Server thread/WARN]: Couldn't find resource table railcraft:chests/village_workshop
[11:18:44] [Server thread/INFO]: Preparing start region for level 0
[11:18:44] [Server thread/WARN]: Skipping Piece with id agricraft:Greenhouse
[11:18:44] [Server thread/WARN]: Skipping Piece with id agricraft:GreenhouseIrrigated
[11:18:45] [Server thread/INFO]: Preparing spawn area: 17%
[11:18:46] [Server thread/INFO]: Preparing spawn area: 93%
[11:18:47] [Server thread/WARN]: Couldn't find resource table railcraft:chests/village_workshop
[11:18:48] [Server thread/INFO]: FTBLib: Server reloaded in 19ms
[11:18:48] [Server thread/INFO]: Changing view distance to 12, from 10
[11:18:50] [Server thread/INFO]: CalabazY[local:E:964b103e] logged in with entity id 900 at (131.43707564570627, 37.0, -241.12270430016122)
[11:18:50] [Server thread/INFO]: CalabazY joined the game
[11:18:52] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2349ms behind, skipping 46 tick(s)
[11:19:04] [Thread-10/INFO]: [CHAT] §2MorePlayerModels§f installed. More info at §9§nClick here
[11:19:04] [Server thread/INFO]: Saving and pausing game...
[11:19:04] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:19:04] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Nether
[11:19:05] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/The End
[11:19:05] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Deep Dark
[11:19:05] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:19:08] [Client thread/INFO]: [CHAT] [Cyclops Core] Update available: 0.10.0 [Download]
[11:19:08] [Client thread/INFO]: [CHAT] [Cyclops Core]§f Fix cube detection crash
[11:19:09] [Client thread/INFO]: [CHAT] Veinminer using client keybind. See mod config for details.
[11:19:09] [Client thread/INFO]: [CHAT] Veinminer client keybind set to activate on pressing the key.
[11:19:09] [Server thread/INFO]: Saving and pausing game...
[11:19:09] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:19:09] [Client thread/INFO]: [CHAT] InvTweaks: Configuration loaded.
[11:19:09] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Nether
[11:19:10] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/The End
[11:19:10] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Deep Dark
[11:19:10] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:19:16] [Client thread/INFO]: [CHAT] Version 2.4.1.102 of CodeChickenCore is available
[11:19:16] [Client thread/INFO]: [CHAT] Version 2.2.1.106 of EnderStorage is available
[11:19:16] [Client thread/INFO]: [CHAT] Version 2.1.3.207 of NotEnoughItems is available
[11:19:16] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bM§f]
[11:19:20] [Server thread/INFO]: Saving and pausing game...
[11:19:20] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:19:20] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Nether
[11:19:20] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/The End
[11:19:21] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Deep Dark
[11:19:21] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:19:22] [Server thread/WARN]: CalabazY moved wrongly!
[11:19:31] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 8475ms behind, skipping 169 tick(s)
[11:20:05] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 25624ms behind, skipping 512 tick(s)
[11:20:13] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 8245ms behind, skipping 164 tick(s)
[11:20:24] [Server thread/INFO]: CalabazY fell out of the world
[11:20:24] [Server thread/INFO]: [CalabazY: Killed CalabazY]
[11:20:24] [Client thread/INFO]: [CHAT] CalabazY fell out of the world
[11:20:24] [Client thread/INFO]: [CHAT] Killed CalabazY
[11:20:33] [Server thread/INFO]: Saving and pausing game...
[11:20:33] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:20:34] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:216) [bzl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:134) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:130) ~[ahp.class:?]
	at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:132) ~[ahq.class:?]
	at net.minecraft.entity.passive.EntityVillager.func_70014_b(EntityVillager.java:301) ~[zn.class:?]
	at com.inventorypets.EntityBillGates.func_70014_b(EntityBillGates.java:248) ~[EntityBillGates.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582) ~[rw.class:?]
	... 11 more
[11:20:34] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Nether
[11:20:34] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:20:34] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 12786ms behind, skipping 255 tick(s)
[11:20:43] [Server thread/INFO]: Saving and pausing game...
[11:20:43] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:20:43] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:216) [bzl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:134) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:130) ~[ahp.class:?]
	at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:132) ~[ahq.class:?]
	at net.minecraft.entity.passive.EntityVillager.func_70014_b(EntityVillager.java:301) ~[zn.class:?]
	at com.inventorypets.EntityBillGates.func_70014_b(EntityBillGates.java:248) ~[EntityBillGates.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582) ~[rw.class:?]
	... 11 more
[11:20:43] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:20:43] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6856ms behind, skipping 137 tick(s)
[11:21:26] [Server thread/INFO]: Saving and pausing game...
[11:21:26] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:21:26] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:216) [bzl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:134) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:130) ~[ahp.class:?]
	at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:132) ~[ahq.class:?]
	at net.minecraft.entity.passive.EntityVillager.func_70014_b(EntityVillager.java:301) ~[zn.class:?]
	at com.inventorypets.EntityBillGates.func_70014_b(EntityBillGates.java:248) ~[EntityBillGates.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582) ~[rw.class:?]
	... 11 more
[11:21:26] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:21:27] [Server thread/INFO]: Stopping server
[11:21:27] [Server thread/INFO]: Saving players
[11:21:27] [Server thread/INFO]: Saving worlds
[11:21:27] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/Overworld
[11:21:27] [Server thread/INFO]: Saving chunks for level 'Iskallian Cult'/ExtraUtils2_Quarry_Dim
[11:26:02] [Client thread/INFO]: Stopping!
[11:26:02] [Client thread/INFO]: SoundSystem shutting down...
[11:26:02] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by calabazY** [comment]
didn't have any bad sectors and the drive has 25g left

**Comment by calabazY** [comment]
I think it is fixed

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
