### ISSUE TITLE
ORE GEN PROBS

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#544]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
SO this what happened 
i finally got foolcraft to run (see my old thread) and then i updated to 1.4.3 and then since i didnt feel it was safe playing my old worlds due to crashes in them and mostly just getting bored of them,
i decided to make a new world , and then i did everything made it and then i go into a cave and discover ORE GEN IS SOO BROKEN,I FOUND SILICON AND SULFUR AT Y-68!

## Reproduce Steps
Well im not sure how but i named my world CRAFT OF ZE FOOLZ ant the seed is (your going to laugh hard right now) "github.com/scalda/FoolCraft/issues" yes it reaaly is that ,i wrote that as seed :)

## Additional Information

i am posting my log just in case BOP sent some potent info in the log
[latest.txt](https://github.com/scalda/FoolCraft/files/1073558/latest.txt)
and yeah im refraining from playing cause i think it would be cheaty to mine all dia lvl ores at y=68
Screenshots

![2017-06-14_10 22 38](https://user-images.githubusercontent.com/26516505/27116128-0d280b2a-50ed-11e7-9036-4c60bcdd66f1.png)
![2017-06-14_10 22 43](https://user-images.githubusercontent.com/26516505/27116131-0d2b23be-50ed-11e7-8bdb-d8cdac7c0e14.png)
![2017-06-14_10 23 02](https://user-images.githubusercontent.com/26516505/27116132-0d2efbb0-50ed-11e7-9374-0e90f87867ff.png)
![2017-06-14_10 23 21](https://user-images.githubusercontent.com/26516505/27116130-0d2a27c0-50ed-11e7-9823-40faa6e1440b.png)
![2017-06-14_10 24 10](https://user-images.githubusercontent.com/26516505/27116135-0d675fb4-50ed-11e7-93d4-18f827d4cf54.png)
![2017-06-14_10 24 14](https://user-images.githubusercontent.com/26516505/27116136-0d6891a4-50ed-11e7-966b-90ae32f8d73f.png)

So yeah you see

**Comment by ajdjyt** [comment]
i just realised all the ores are modern warfare!!! somehow you guys that is the devs turned on modern warfare ore gen ,which was off since foolcraft 1.0 ?why did you do that?

**Comment by ajdjyt** [comment]
now which line do i edit in mordern warfares .cfg files to disable this so that i can play foolcraft before 1.4.4 or 1.5

**Comment by ajdjyt** [comment]
wow two of the modern warfare .cfg files are invalid look
![screenshot 181](https://user-images.githubusercontent.com/26516505/27116274-e8f432b4-50ed-11e7-885c-26c1b7c3d559.png)

**Comment by scalda** [comment]
ok, thanks for bringing this to me attention i will redo the oregen for MW for 1.4.4 today and get a fix out for it. MW has had a lot of changes over the last couple weeks

**Comment by ajdjyt** [comment]
Ok saclda

**Comment by ajdjyt** [comment]
btw is there a way I can make these files valid so that I can play foolcraft before 1.4.4 or will .1.4.4 get released in under a 3 or 5 days then I'm fine

**Comment by ajdjyt** [comment]
oh and the log points to some stuff here
09:54:58] [Client thread/ERROR]: Failed to parse configuration: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; systemId: file:/C:/Users/AJ%20DJ/Documents/Curse/Minecraft/Instances/FoolCraft%20(2)/config/ModernWarfare.cfg; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]
javax.xml.bind.UnmarshalException
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) ~[?:1.8.0_25]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563) ~[?:1.8.0_25]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249) ~[?:1.8.0_25]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221) ~[?:1.8.0_25]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276) ~[?:1.8.0_25]
	at com.vicmatskiv.weaponlib.config.ConfigurationManager$Builder.createConfiguration(ConfigurationManager.java:104) [ConfigurationManager$Builder.class:?]
	at com.vicmatskiv.weaponlib.config.ConfigurationManager$Builder.build(ConfigurationManager.java:96) [ConfigurationManager$Builder.class:?]
	at com.vicmatskiv.mw.ModernWarfareMod.initConfigurationManager(ModernWarfareMod.java:106) [ModernWarfareMod.class:?]
	at com.vicmatskiv.mw.ModernWarfareMod.init(ModernWarfareMod.java:79) [ModernWarfareMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_25]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649) ~[?:1.8.0_25]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) ~[?:1.8.0_25]
	... 42 more

**Comment by ajdjyt** [comment]
![screenshot 184](https://user-images.githubusercontent.com/26516505/27124783-beb3cdc6-510f-11e7-98ed-f4051b245dc6.png)
should the values in the file im showcasing here equal to 0? cause i remember ore spawns from modern warfare were blocked since foolcraft 1.0 and i think rendog or iskall himself has once mentioned in either of their foolcraft videos that ore spawns for modern warfare are disabled due to other mods spawning there own ores.

**Comment by ajdjyt** [comment]
Are you going to release a hotfix?
If not is there a way I can hotfix this for the  - time-being?

And if MW is not a core mode can i remove it all together since I don't use them alot anyways?
Nvm what I said in the previous line cause then it would cause a need for a change in the docmm77 lootbag loot:( due to " the docinator" and if I remove MW and open a docmm77 lootbag ta-da
I'll create an unexpected exception and crash!

**Comment by scalda** [comment]
1.4.4 release will be out later tonight london time

**Comment by ajdjyt** [comment]
Ok thanx scalda

**Comment by ajdjyt** [comment]
Thanks 1.4.4 fixed it
