### ISSUE TITLE
Game crash on join from extrautils2

### ISSUE THREAD

**Issue by WazUpItsZion** [scalda/FoolCraft#569]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

When joining my single player world, I automatically crash without ever getting into the world. Where I am logging in, I have Refined Storage items. (such as grids, crafters, transceivers, disk drives)

## Reproduce Steps

Not quite sure.

## Additional Information

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlusTiC (plustic-5.0.1.3.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.8.107-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.2.157-universal.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/26/17 11:33 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.resetChunkBlocks(WorldProviderSpecialDim.java:127)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.releaseChunk(WorldProviderSpecialDim.java:154)
	at com.rwtema.extrautils2.quarry.TileQuarry.getNewChunk(TileQuarry.java:414)
	at com.rwtema.extrautils2.quarry.TileQuarry.advance(TileQuarry.java:409)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:307)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.resetChunkBlocks(WorldProviderSpecialDim.java:127)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.releaseChunk(WorldProviderSpecialDim.java:154)
	at com.rwtema.extrautils2.quarry.TileQuarry.getNewChunk(TileQuarry.java:414)
	at com.rwtema.extrautils2.quarry.TileQuarry.advance(TileQuarry.java:409)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:307)

-- Block entity being ticked --
Details:
	Name: XU2:TileQuarry // com.rwtema.extrautils2.quarry.TileQuarry
	Block type: ID #276 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-174,30,37), Chunk: (at 2,1,5 in -11,2; contains blocks -176,0,32 to -161,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #276 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: TEST WORLD
	All players: 1 total; [EntityPlayerMP['WazUpItsZion'/446, l='TEST WORLD', x=-185.30, y=17.71, z=28.98]]
	Chunk stats: ServerChunkCache: 377 Drop: 0
	Level seed: 7327031353071995738
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-112,64,144), Chunk: (at 0,4,0 in -7,9; contains blocks -112,0,144 to -97,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4079606 game time, 1069 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 46045 (now: false), thunder time: 34341 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by scalda** [comment]
This is you Exu2 quarry is causing issues I have seen this on iskalls patreon server of where 2 quarries are in close proximity to one another. my suggestion is to go into your config folder locate the forge.cfg file and change these 2 lines to true and you will be able to reload the pack and log in and remove the block at the location stated in the crash report. but make sure you set them lines back to false once done.

`# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false`

`    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false`

**Comment by WazUpItsZion** [comment]
I still got an error when joining my single-player world with the enabled settings above. Everything loads when I join and right when everything loads (before I am able to open chat or anything) the game crashes.

Here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlusTiC (plustic-5.0.1.3.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.8.107-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.2.157-universal.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/28/17 8:49 AM
Description: Exception ticking world entities

java.util.UnknownFormatConversionException: Conversion = '2'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at net.minecraftforge.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:78)
	at net.minecraftforge.fml.common.FMLLog.log(FMLLog.java:37)
	at net.minecraftforge.fml.common.FMLLog.severe(FMLLog.java:52)
	at net.minecraft.world.World.func_72939_s(World.java:1814)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at net.minecraftforge.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:78)
	at net.minecraftforge.fml.common.FMLLog.log(FMLLog.java:37)
	at net.minecraftforge.fml.common.FMLLog.severe(FMLLog.java:52)
	at net.minecraft.world.World.func_72939_s(World.java:1814)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: TEST WORLD
	All players: 1 total; [EntityPlayerMP['WazUpItsZion'/417, l='TEST WORLD', x=-185.30, y=17.71, z=28.98]]
	Chunk stats: ServerChunkCache: 380 Drop: 0
	Level seed: 7327031353071995738
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-112,64,144), Chunk: (at 0,4,0 in -7,9; contains blocks -112,0,144 to -97,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4079966 game time, 1069 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 45685 (now: false), thunder time: 33981 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
