### ISSUE TITLE
Crash due to Ticking Entity (chickens)

### ISSUE THREAD

**Issue by Necro9227** [scalda/FoolCraft#607]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
searching for a solution to a ticking entity in world, as every time I log into my world I instantly crash, according to the crash report the culprit is one of Chickens mods chickens which I was placing in pens after storing all their eggs a few versions back. 

## Reproduce Steps

Every time I log into my world I instantly crash, according to the crash report the culprit is one of Chickens mods chickens.

## Additional Information
Time: 7/13/17 2:31 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.setycz.chickens.chicken.EntityChickensChicken.func_70636_d(EntityChickensChicken.java:146)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- Head --
Thread: Server thread
Stacktrace:
	at com.setycz.chickens.chicken.EntityChickensChicken.func_70636_d(EntityChickensChicken.java:146)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: chickens.ChickensChicken (com.setycz.chickens.chicken.EntityChickensChicken)
	Entity ID: 312
	Entity Name: ~~ERROR~~ NullPointerException: null
	Entity's Exact location: -617.76, 55.00, -1274.38
	Entity's Block location: World: (-618,55,-1275), Chunk: (at 6,3,5 in -39,-80; contains blocks -624,0,-1280 to -609,255,-1265), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: survival World
	All players: 1 total; [EntityPlayerMP['Necro9227'/316, l='survival World', x=-612.56, y=57.00, z=-1271.61]]
	Chunk stats: ServerChunkCache: 1066 Drop: 0
	Level seed: 86281
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":false,"generateBopTrees":true,"generateBopGrasses":false,"generateBopFoliage":false,"generateBopFlowers":false,"generateBopPlants":false,"generateBopWaterPlants":false,"generateBopMushrooms":false,"generateRockFormations":false,"generatePoisonIvy":false,"generateFlax":true,"generateBerryBushes":true,"generateThorns":false,"generateQuicksand":false,"generateLiquidPoison":true,"generateHotSprings":false,"generateNetherHives":false,"generateNetherPlants":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (252,64,256), Chunk: (at 12,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12887857 game time, 10731968 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 24921 (now: false), thunder time: 22758 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

If requested i could provide a copy of the world.

**Comment by csokasg** [comment]
have you tried this?
https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows

**Comment by Necro9227** [comment]
That did the trick, thankyou.
