### ISSUE TITLE
One of my players started crashing the server with this error

### ISSUE THREAD

**Issue by Schaefer78** [scalda/FoolCraft#706]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
A user created a wither farm with a sheild generator and when the wither dies it produces the following error:
[18:23:31] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at mal.lootbags.handler.BagHandler.isBagEmpty(BagHandler.java:116) ~[BagHandler.class:?]
        at mal.lootbags.item.LootbagItem.getEntityLifespan(LootbagItem.java:435) ~[LootbagItem.class:?]
        at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:66) ~[yk.class:?]
        at net.minecraft.entity.Entity.func_70099_a(Entity.java:1772) ~[rw.class:?]
        at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:548) ~[sg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1080) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970) ~[sf.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) ~[yx.class:?]
        at net.minecraft.entity.boss.EntityWither.func_70097_a(EntityWither.java:550) ~[xv.class:?]
        at mcjty.rftools.blocks.shield.ShieldTEBase.applyDamageToEntity(ShieldTEBase.java:536) ~[ShieldTEBase.class:?]
        at mcjty.rftools.blocks.shield.TickShieldBlockTileEntity.handleDamage(TickShieldBlockTileEntity.java:47) ~[TickShieldBlockTileEntity.class:?]
        at mcjty.rftools.blocks.shield.TickShieldBlockTileEntity.func_73660_a(TickShieldBlockTileEntity.java:22) ~[TickShieldBlockTileEntity.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more

## Reproduce Steps
Make a wither and let a shield generator kill it. We did a test and the server crashed 2 x out of 9 withers killed by it.

**Comment by Schaefer78** [comment]
Just seen there is another post with this issue. Close this one if u wish.
