### ISSUE TITLE
my world dont strat

### ISSUE THREAD

**Issue by karlsson4444** [scalda/FoolCraft#821]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
my world dont start it only say loading world building terrain
it did crash and then i cant start my world

**Comment by svennieke** [comment]
any chance that you have the crashlog? this might be useful to see why the crash happend in the first place, as i know when i was testing stuff i also had a world crash, needed to delete certain entities and blocks via MCedit, i want to take a look if you have the same issue

**Comment by karlsson4444** [comment]
yea i have

**Comment by karlsson4444** [comment]
Exception loading model for variant avaritia:block_resource#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:item/block_resource with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153)
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:328)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:148)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: avaritia:models/item/block_resource.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:311)
	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:879)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	... 14 more

**Comment by Mrbysco** [comment]
The part you stated is not the crash source. It's forge saying that a json or texture that a block is trying to use (In this case Avaritia's Block Resource) can't be loaded as it can't be found. This would only result in a missing error block.

Could you upload the last crash log you had to a website like [Pastebin](https://pastebin.com/).
The one before you were unable to load your world?

**Comment by karlsson4444** [comment]
i dont know how

**Comment by karlsson4444** [comment]
that is everything i get

**Comment by karlsson4444** [comment]
i got this today
https://pastebin.com/GerV6Lyv

**Comment by Mrbysco** [comment]
You're using the Twitch launcher?
if so you can get to the crash log by doing the next few things:
1) Right click the mod pack.
2) Click "Open folder".
3) Go to the folder called "crash-reports".
4) Find the latest crash log and open it.
5) Put the full crash log on [Pastebin](https://pastebin.com/).

**Comment by karlsson4444** [comment]
there we go
https://pastebin.com/n3rk4L68

**Comment by karlsson4444** [comment]
sorry wrong

**Comment by karlsson4444** [comment]
https://pastebin.com/r4f4brQY

**Comment by svennieke** [comment]
sorry i can't help you with this one, is nowhere near close to the crashing issue i had, my best bet would be to load up a backup of the world

**Comment by svennieke** [comment]
maybe it has something to do with this, you never know https://twitter.com/Dinnerbone/status/923204144948752384

**Comment by Schaefer78** [comment]
Have you tried re-installing Java? uninstall and install java. the Java UTF string i've seen before were a bad java build / install. Worth a try

**Comment by scalda** [comment]
any news on this @karlsson4444 if it's fixed please close the issue
