### ISSUE TITLE
Server crashes with error

### ISSUE THREAD

**Issue by Facomen** [scalda/FoolCraft#913]
<!-->
- [ x] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ x] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x ] I am crashing and can provide my crash report(s)

[01:22:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.mramericanmike.cropdusting.events.EntityTickEvent.onEntityTick(EntityTickEvent.java:50) ~[EntityTickEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_798_EntityTickEvent_onEntityTick_LivingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:177) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.getContainerItem(ForgeHooks.java:923) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.defaultRecipeGetRemainingItems(ForgeHooks.java:900) ~[ForgeHooks.class:?]
	at net.minecraftforge.oredict.ShapedOreRecipe.func_179532_b(ShapedOreRecipe.java:281) ~[ShapedOreRecipe.class:?]
	at mcjty.lib.tools.InventoryTools.getRemainingItems(InventoryTools.java:43) ~[InventoryTools.class:?]
	at mcjty.rftools.blocks.crafter.CrafterBaseTE.craftOneItemNew(CrafterBaseTE.java:352) ~[CrafterBaseTE.class:?]
	at mcjty.rftools.blocks.crafter.CrafterBaseTE.craftOneCycle(CrafterBaseTE.java:313) ~[CrafterBaseTE.class:?]
	at mcjty.rftools.blocks.crafter.CrafterBaseTE.checkStateServer(CrafterBaseTE.java:294) ~[CrafterBaseTE.class:?]
	at mcjty.rftools.blocks.crafter.CrafterBaseTE.func_73660_a(CrafterBaseTE.java:279) ~[CrafterBaseTE.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[01:22:33] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Administrator\Desktop\servidor\.\crash-reports\crash-2017-12-30_01.22.33-server.txt
[01:22:33] [Server thread/INFO]: Stopping server
[01:22:33] [Server thread/INFO]: Saving players
[01:22:33] [Server thread/INFO]: Saving worlds
[01:22:33] [Server thread/INFO]: Saving chunks for level 'FoolCraft'/Overworld
[01:22:34] [Server thread/INFO]: Saving chunks for level 'FoolCraft'/The End
[01:22:34] [Server thread/INFO]: Saving chunks for level 'FoolCraft'/The Beneath
[01:22:34] [Server thread/INFO]: Saving chunks for level 'FoolCraft'/ExtraUtils2_Quarry_Dim
[crash-2017-12-30_01.22.33-server.txt](https://github.com/scalda/FoolCraft/files/1594780/crash-2017-12-30_01.22.33-server.txt)

**Comment by scalda** [comment]
this block is the bad one casuing you issues
`-- Block entity being ticked --
Details:
	Name: rftools_crafter3 // mcjty.rftools.blocks.crafter.CrafterBlockTileEntity3
	Block type: ID #2484 (tile.rftools.crafter3 // mcjty.rftools.blocks.crafter.CrafterBlock)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-112,69,-8), Chunk: (at 0,4,8 in -7,-1; contains blocks -112,0,-16 to -97,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #2484 (tile.rftools.crafter3 // mcjty.rftools.blocks.crafter.CrafterBlock)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)`

you will either need to mcedit out the block at that location or you can try this [fix](https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows)
