### ISSUE TITLE
Chunk Loading Bug

### ISSUE THREAD

**Issue by Dogatron03** [scalda/FoolCraft#95]
Hey, 
In Xisumanati in 1.7.10 I had a bug with chunks not loading properly and having to relog to get them to load. Today I found the same bug with FoolCraft but when I do relog my game crashes with the following error. I am in Version 1.2.1 with no modifications. I also played hermitpack with no problems. I think it might be caused by a mod like Thermal Expansion that has only just been updated to 1.10 from 1.7.10.

Dogatron03

Error Message from latest.log: 
[17:04:52] [Server thread/ERROR]: The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. This is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available.
[17:04:52] [Server thread/ERROR]: A fatal exception occurred during the server about to start event
java.lang.RuntimeException: The ForgeModLoader state engine is invalid
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:183) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:926) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:04:52] [Server thread/INFO]: Stopping server
[17:04:52] [Server thread/INFO]: Saving players
[17:04:52] [Server thread/INFO]: Saving worlds
[17:05:07] [Server thread/INFO]: Applying holder lookups
[17:05:07] [Server thread/INFO]: Holder lookups applied
[17:05:07] [Server thread/INFO]: RFTools: server is stopping. Shutting down gracefully
[17:05:07] [Server thread/INFO]: The state engine was in incorrect state AVAILABLE and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:05:08] [Server thread/INFO]: Applying holder lookups
[17:05:08] [Server thread/INFO]: Holder lookups applied
[17:05:08] [Server thread/ERROR]: Skipping event FMLServerStoppedEvent and marking errored mod ftbu since required dependency ftbl has errored
[17:05:08] [Server thread/INFO]: RFTools: server is stopping. Shutting down gracefully
[17:05:08] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:05:08] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by scalda** [comment]
can you provide the crash report via pastebin please

**Comment by Dogatron03** [comment]
Sorry for the late reply here u go:
https://pastebin.com/J1tF3ESJ

**Comment by Jo-Mamma75** [comment]
@Dogatron03 
What is the current status on this issue?  I see that @scalda has not replied since you posted the pastebin of the crash log.  Has the issue persisted since the 1.2.2 update of the pack?

**Comment by scalda** [comment]
@Dogatron03 have you tried 1.2.2? if so are you still getting these issues?

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
